# Generated by Django 2.1.4 on 2018-12-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=120, verbose_name='Файл картинки')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Описание')),
                ('alt', models.TextField(verbose_name='Подсказка')),
                ('index', models.IntegerField(verbose_name='Индекс')),
            ],
            options={
                'db_table': 'app_ideator_visuals',
            },
        ),
    ]
