# Generated by Django 2.1.4 on 2018-12-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectone', '0002_visual'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visual',
            table=None,
        ),
    ]
