# Generated by Django 2.1.4 on 2018-12-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectone', '0004_auto_20181214_1316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albums',
            new_name='Album',
        ),
    ]
